---
- name: Set bash prompt on servers
  hosts: all
  become: yes
  vars:
    bash_prompt: '\u@\h:\w\$ '

  tasks:

    - name: Update /etc/profile with custom bash prompt if not already set
      lineinfile:
        path: /etc/profile
        regexp: '^export PS1='
        line: "export PS1='{{ bash_prompt }}'"
        state: present
        create: yes
        backrefs: yes

    - name: Update /etc/skel/.bashrc with custom bash prompt if not already set
      lineinfile:
        path: /etc/skel/.bashrc
        regexp: '^export PS1='
        line: "export PS1='{{ bash_prompt }}'"
        state: present
        create: yes
        backrefs: yes
