---
- name: Set bash prompt on servers
  hosts: all
  become: true
  become_user: root

  vars:
    bash_prompt: '\u@\h:\w\$ '

  tasks:

    - name: Copy colorprompt.sh from template
      template:
        src: colorprompt.sh.j2
        dest: /etc/profile.d/colorprompt.sh
        owner: root
        group: root
        mode: '0755'

    - name: Ensure /etc/profile sets custom bash prompt if not already present
      lineinfile:
        path: /etc/profile
        regexp: '^export PS1='
        line: "export PS1='{{ bash_prompt }}'"
        state: present
        create: yes

    - name: Ensure /etc/skel/.bashrc sets custom bash prompt if not already present
      lineinfile:
        path: /etc/skel/.bashrc
        regexp: '^export PS1='
        line: "export PS1='{{ bash_prompt }}'"
        state: present
        create: yes
