---
- name: Configure dynamic bash prompt for all users
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Install PS1 script for all users
      template:
        src: colorprompt.sh.j2
        dest: /etc/profile.d/colorprompt.sh
        owner: root
        group: root
        mode: '0644'

    - name: Ensure colorprompt is sourced in /etc/bash.bashrc
      lineinfile:
        path: /etc/bash.bashrc
        line: '[[ $- == *i* ]] && [ -f /etc/profile.d/colorprompt.sh ] && source /etc/profile.d/colorprompt.sh'
        state: present
        create: yes
        insertafter: EOF

    - name: Ensure colorprompt is sourced in /etc/skel/.bashrc
      lineinfile:
        path: /etc/skel/.bashrc
        line: |
          # at the end of /etc/skel/.bashrc
          if [ -f /etc/profile.d/colorprompt.sh ]; then
              . /etc/profile.d/colorprompt.sh
          fi
        state: present
        create: yes
        insertafter: EOF

    - name: Gather all normal users' home directories
      command: getent passwd
      register: passwd_entries
      changed_when: false

    - name: Ensure existing users source /etc/bash.bashrc
      lineinfile:
        path: "{{ item }}/.bashrc"
        line: '[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc'
        state: present
        insertafter: BOF
      loop: >-
        {{
          passwd_entries.stdout_lines
          | map('split', ':')
          | selectattr('2', 'int', '>=', 1000)
          | selectattr('0', 'ne', 'nobody')
          | map('extract', [5])
          | list
        }}
      loop_control:
        label: "{{ item }}"
      become: yes
      become_user: root

    - name: Debug - list /etc/profile.d to confirm file exists
      command: ls -alh /etc/profile.d/
      register: profile_d_listing
      become: yes
      become_user: root

    - name: Show /etc/profile.d contents
      debug:
        var: profile_d_listing.stdout_lines
