---
- name: Configure dynamic bash prompt for all users
  hosts: all
  become: yes

  tasks:
    - name: Install PS1 script for all users
      template:
        src: colorprompt.sh.j2
        dest: /etc/profile.d/colorprompt.sh
        owner: root
        group: root
        mode: '0644'
      become: true
      become_user: root

    - name: Ensure colorprompt is sourced in all interactive shells
      lineinfile:
        path: /etc/bash.bashrc
        line: '[[ $- == *i* ]] && [ -f /etc/profile.d/colorprompt.sh ] && source /etc/profile.d/colorprompt.sh'
        state: present
        create: yes
        insertafter: EOF
      become: true
      become_user: root

    - name: Debug - list /etc/profile.d to confirm file exists
      command: ls -alh /etc/profile.d/
      register: profile_d_listing
      become: true
      become_user: root

    - name: Show /etc/profile.d contents
      debug:
        var: profile_d_listing.stdout_lines
